#    Copyright (C) 2017  Jesús Donaldo Osornio Hernández
#    Copyright (C) 2017  Luis Alejandro Herrera León
#    Copyright (C) 2017  Gabriel Alejandro López Morteo
#
#    This file is part of DataPlugin.
#
#    DataPlugin is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    DataPlugin is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with DataPlugin.  If not, see <http://www.gnu.org/licenses/>.

config:
  plugin-dir: /home/jdosornio/IdeaProjects/dataplugin/plugins/load
  catalog-database: metadata
  mongodb-username: root
  mongodb-password: mongo
  mongodb-authdb: admin
  mongodb-host: localhost
  mongodb-port: 27017
  pg-username: postgres
  pg-password: postgres
  pg-host: localhost
  pg-port: 5432
  pg-raster-db: griddb
  # log-file ->
  # landing-area ->
